--- #YAML:1.0
name: Win32-Pipe
abstract: Win32 Named Pipe
version: 0.026
author:
  - Dave Roth <rothd@roth.net>
  - Jan Dubois <jand@activestate.com>
license: perl
requires: 
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jandubois/win32-pipe
meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Jan Dubois
